name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  id-token: write
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    env:
      PYTHON_VERSION: "3.11"

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: pdm-project/setup-pdm@v3
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: true
      - name: Install dependencies
        run: pdm install -v --dev

      - name: Build
        run: |
          pdm build -v
      - name: Publish release distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
          generate_release_notes: true
