name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  id-token: write
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    env:
      PYTHON_VERSION: "3.11"

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install poetry
        run: pipx install poetry
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'poetry'
      - name: Install dependencies
        run: poetry install --no-interaction --no-root

      - name: Build
        run: |
          poetry build -vvv
      - name: Publish release distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
          generate_release_notes: true
